export const PRICING_TIERS = [
  {
    id: 'starter',
    name: 'Starter',
    monthlyPrice: 99,
    callLimit: 40,
    description: 'For solo operators just getting started',
    cta: 'Start Free Trial',
    ctaHref: '/onboarding',
    highlighted: false,
    features: [
      'AI receptionist 24/7',
      'Lead capture & CRM',
      'SMS + email notifications',
      'Priority triage engine',
      'Google Calendar sync',
      'Outlook Calendar sync',
      'Booking-first dispatcher',
      'Multi-language (EN/ES)',
      'Recovery SMS fallback',
      'Up to 40 calls/month',
      'Email support',
    ],
  },
  {
    id: 'growth',
    name: 'Growth',
    monthlyPrice: 249,
    callLimit: 120,
    description: 'For growing crews booking 3-5 jobs per day',
    cta: 'Start Free Trial',
    ctaHref: '/onboarding',
    highlighted: true,
    badge: 'Most Popular',
    features: [
      'AI receptionist 24/7',
      'Lead capture & CRM',
      'SMS + email notifications',
      'Priority triage engine',
      'Google Calendar sync',
      'Outlook Calendar sync',
      'Booking-first dispatcher',
      'Multi-language (EN/ES)',
      'Recovery SMS fallback',
      'Up to 120 calls/month',
      'Priority email support',
    ],
  },
  {
    id: 'scale',
    name: 'Scale',
    monthlyPrice: 599,
    callLimit: 400,
    description: 'For multi-crew operations running at full capacity',
    cta: 'Start Free Trial',
    ctaHref: '/onboarding',
    highlighted: false,
    features: [
      'AI receptionist 24/7',
      'Lead capture & CRM',
      'SMS + email notifications',
      'Priority triage engine',
      'Google Calendar sync',
      'Outlook Calendar sync',
      'Booking-first dispatcher',
      'Multi-language (EN/ES)',
      'Recovery SMS fallback',
      'Up to 400 calls/month',
      'Priority support + onboarding call',
    ],
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    monthlyPrice: null,
    callLimit: null,
    description: 'For franchises and multi-location operations',
    cta: 'Contact Us',
    ctaHref: '/contact?type=sales',
    highlighted: false,
    features: [
      'AI receptionist 24/7',
      'Lead capture & CRM',
      'SMS + email notifications',
      'Priority triage engine',
      'Google Calendar sync',
      'Outlook Calendar sync',
      'Booking-first dispatcher',
      'Multi-language (EN/ES)',
      'Recovery SMS fallback',
      'Unlimited calls',
      'Dedicated account manager',
      'Custom integrations',
    ],
  },
];

export const COMPARISON_FEATURES = [
  { name: 'Monthly calls', starter: '40', growth: '120', scale: '400', enterprise: 'Unlimited' },
  { name: 'Annual calls', starter: '480', growth: '1,440', scale: '4,800', enterprise: 'Unlimited' },
  { name: 'Support level', starter: 'Email', growth: 'Priority email', scale: 'Priority + onboarding', enterprise: 'Dedicated' },
  { name: 'AI receptionist 24/7', starter: true, growth: true, scale: true, enterprise: true },
  { name: 'Lead capture & CRM', starter: true, growth: true, scale: true, enterprise: true },
  { name: 'SMS + email notifications', starter: true, growth: true, scale: true, enterprise: true },
  { name: 'Priority triage engine', starter: true, growth: true, scale: true, enterprise: true },
  { name: 'Google Calendar sync', starter: true, growth: true, scale: true, enterprise: true },
  { name: 'Outlook Calendar sync', starter: true, growth: true, scale: true, enterprise: true },
  { name: 'Booking-first dispatcher', starter: true, growth: true, scale: true, enterprise: true },
  { name: 'Multi-language (EN/ES)', starter: true, growth: true, scale: true, enterprise: true },
  { name: 'Recovery SMS fallback', starter: true, growth: true, scale: true, enterprise: true },
  { name: 'Custom integrations', starter: false, growth: false, scale: false, enterprise: true },
];

export function getAnnualPrice(monthlyPrice) {
  if (monthlyPrice === null) return null;
  return Math.round(monthlyPrice * 0.8);
}
